#spring.application.name=Journal App
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.uri=mongodb+srv://kingKaiser:c2VB6to49oVIS3q4@cluster0.zaaeb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#spring.main.allow-circular-references=true

# Now here we observe that spring.data.mongodb is common, and we have to write it again and again for adding a new property
# Therefore we can use yml file where we can write common part only for a single time and add configuration that is required that's it.

#Syntax

spring:
  main: # Here Spring.main is common part
    allow-circular-references: true # here we will add many properties inside "Spring.main"
  application: # This is common part "Spring.application"
    name: Journal App # properties inside "spring.application"
  data:
    mongodb: # Common part "Spring.data.mongodb"
      uri: mongodb+srv://kingKaiser:c2VB6to49oVIS3q4@cluster0.zaaeb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb # These are the properties under "spring.data.mongodb"
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journalApplication